AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Date Difference API using Lambda and spring boot.

Resources:
  DateDifferenceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.ashupan.lambda.LambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/date-difference-service-1.0.0-SNAPSHOT.jar
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  DateDifferenceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/languages'
    Export:
      Name: DateDifferenceApi
